#!/bin/bash
############################
# This script creates symlinks from the home directory to any desired dotfiles in ~/dotfiles
# Based on awesome https://github.com/michaeljsmalley/dotfiles/blob/master/makesymlinks.sh
###########################

########## Variables

dir=~/dotfiles                    # dotfiles directory
files="vimrc zshrc"               # list of files/folders to symlink in homedir
username="czarnodziej"            # name of personal config files

##########

for file in $files; do
    echo "Backing up old version and creating symlink to $file in home directory."
    mv -vf ~/.$file ~/.$file.old
    ln -sf $dir/$file ~/.$file
done

install_zsh () {
# Test to see if zshell is installed.  If it is:
if [ -f /bin/zsh -o -f /usr/bin/zsh ]; then
    # Clone my oh-my-zsh repository from GitHub only if it isn't already present
    if [ ! -d ~/.oh-my-zsh/ ]; then
	curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
	ln -sf $dir/zshrc ~/.$file
	#symlink plugin with personal aliases...
	mkdir ~/.oh-my-zsh/custom/plugins/$username;
	ln -s $dir/$username.plugin.zsh ~/.oh-my-zsh/custom/plugins/$username/$username.plugin.zsh
	#...and bash prompt theme
	mkdir ~/.oh-my-zsh/custom/themes;
	ln -s $dir/$username.zsh-theme ~/.oh-my-zsh/custom/themes/$username.zsh-theme
    fi
    #install powerline theme
    git clone https://github.com/bhilburn/powerlevel9k.git ~/.oh-my-zsh/custom/themes/powerlevel9k
    #syntax highlight
    git clone git://github.com/zsh-users/zsh-syntax-highlighting.git ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
    # Set the default shell to zsh if it isn't currently set to zsh
    if ! [ -n "`$SHELL -c 'echo $ZSH_VERSION'`" ]; then
        chsh -s $(which zsh)
    fi

else
        sudo apt-get install zsh
        install_zsh
fi
}

install_zsh
./install_vim
